name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run integration tests
        run: |
          docker compose \
            -f docker-compose.yaml \
            -f docker-compose.test.yaml \
            up --build --exit-code-from test --abort-on-container-exit

      - name: Tear down containers
        if: always()
        run: docker compose -f docker-compose.yaml -f docker-compose.test.yaml down --volumes --remove-orphans

      - name: Run Balancer unit tests
        working-directory: ./cmd/lb
        run: go test -v .
